org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
mc_version=1.20.1
jei_version=15.20.0.112
forge_version=47.4.0
forge_version_range=[47.3.33,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=ntrials
mod_name=NewTrials
mod_license=MIT
mod_version=1.7.0
mod_group_id=cz.maxtechnik
mod_authors=MaxTechnik, Suriken, LaserLinx, H3xyCZ
mod_description=§fThis mod brings§f§l new items and blocks from the latest Minecraft versions§f into§f§l Minecraft 1.20.1§f,\nallowing players to enjoy fresh content while staying on their favorite version.\n\n§f§lFeatures:\n§f- Added new blocks, items and entities:\n§f - Copper Doors, Copper Bulbs & Copper Trapdoors\n§f - Breeze & Bogged Mobs\n§f - Other blocks and items from the latest versions\n§f- Preserves original mechanics and behavior, just like in vanilla Minecraft.\n\n§f§lRequirements:\n§f- Minecraft §f§l1.20.1\n§f- Forge §f§l47.4.0\n\n§f§lNotes:\n§f- This mod§f§l doesn't just focus on backporting§f vanilla features, it also adds additional content.
